##### 30 сек расчет
- alias: 00_power_conter
  initial_state: true
  trigger:
    - platform: time_pattern
      seconds: '/30'
  action:
##### Потребление телевизор
    - service: mqtt.publish
      data_template:
        topic: "power/01_zigbee_tv/today"
        payload: '{{(states.mqtt_power_today_01_zigbee_tv.state | float +
                    (states.sensor.load_01_zigbee_tv.state | float /120000))|round(5)}}'
        retain: true
    - service: mqtt.publish
      data_template:
        topic: "power/01_zigbee_tv/month"
        payload: '{{(states.sensor.mqtt_power_month_01_zigbee_tv.state | float +
                    (states.sensor.load_01_zigbee_tv.state | float /120000))|round(5)}}'
        retain: true

##### Начало дня    
- alias: 00_power_new_day
  initial_state: true
  trigger:
    - platform: time
      at: '00:00:05'
  action:
##### Запись данных за прошедший день
##### Потребление телевизор
    - service: mqtt.publish
      data_template:
        topic: "power/01_zigbee_tv/yesterday"
        payload: '{{(states.mqtt_power_today_01_zigbee_tv.state | float )|round(5)}}'
        retain: true 

    - delay: 00:00:05

##### Обнуление данных текущего дня
##### Потребление телевизор
    - service: mqtt.publish
      data_template:
        topic: "power/01_zigbee_tv/today"
        payload: '{{ 0.0 }}'
        retain: true

##### Начало месяца
- alias: 00_power_new_ month
  initial_state: true
  trigger:
    - platform: time
      at: '00:00:10'
  condition:
    - condition: template
      value_template: '{{ now().day == 1 }}'
  action:
##### Запись данных за прошедший месяц
##### Потребление телевизор
    - service: mqtt.publish
      data_template:
        topic: "power/01_zigbee_tv/lastmonth"
        payload: '{{(states.sensor.mqtt_power_month_01_zigbee_tv.state | float )|round(5)}}'
        retain: true 
        
    - delay: 00:00:05
##### Обнуление данных текущего месяца
##### Потребление телевизор
    - service: mqtt.publish
      data_template:
        topic: "power/01_zigbee_tv/month"
        payload: '{{ 0.0 }}'
        retain: true
