title: Home Assistant - сервер
views:

  - title: Главная
    id: main
    icon: mdi:home-assistant
    
#    badges:
#      - sensor.time
#      - sensor.date
#      - sensor.home_assistant_v2_db


    cards:

      - type: vertical-stack
        cards:

        - type: markdown
          content: >
             **Google Fit Alex**

        - type: entities
          show_header_toggle: false
          entities:
          - entity: sensor.alex_steps
          - entity: sensor.alex_steps_remain
          - entity: sensor.alex_distance
          - entity: sensor.alex_move_time_custom
          - entity: sensor.alex_heartrate
          - entity: sensor.alex_heartrate_update           
          - entity: sensor.alex_sleep
          - entity: sensor.alex_weight
          - entity: sensor.alex_weight_update

        - type: entities
          title: Система
          show_header_toggle: false
          entities:
            - entity: sensor.time
              name: Текущее время - 
              icon: mdi:clock
              secondary_info: entity-id
            - entity: sensor.date
              name: Дата - 
              icon: mdi:calendar
              secondary_info: entity-id
            - entity: sensor.home_assistant_v2_db
              name: Объем базы данных - 
              icon: mdi:database
              secondary_info: entity-id
            - type: divider            
            - type: call-service
              icon: mdi:database-minus
              name: База данных
              action_name: Сжать
              service: recorder.purge
              service_data:
                keep_days: 1
                repack: true

        - type: horizontal-stack
          cards:

          - type: gauge
            name: Загрузка CPU
            unit: '%'
            entity: sensor.processor_use
            severity:
               green: 0
               yellow: 60
               red: 85 

          - type: gauge
            name: Загрузка ОЗУ
            unit: '%'
            entity: sensor.memory_use_percent
            severity:
               green: 0
               yellow: 60
               red: 85 


      - type: vertical-stack
        cards:

        - type: horizontal-stack
          cards:

          - type: light
            entity: light.yeelight_01_whitebulb
            name: Прихожая
          - type: light
            entity: light.yeelight_05_rgbtvbulb
            name: Гостиная


        - type: entities
          title: Выключатели
          show_header_toggle: false
          entities:
            - entity: light.yeelight_02_ceiling
              name: Yeelight 320 main
            - entity: light.yeelight_02_ceiling_nightlight
              name: Yeelight 320 night
            - entity: switch.plug_158d00010ec4b8
              name: Увлажнитель воздуха
              icon: mdi:air-humidifier
              secondary_info: last-changed
            - entity: switch.plug_158d000114a1e1
              name: Вентилятор
              icon: mdi:fan
              secondary_info: last-changed
            - entity: switch.plug_158d00030a6e78
              name: Настольная лампа
              icon: mdi:desk-lamp
              secondary_info: last-changed
            - entity: script.01_sound_check

      - type: vertical-stack
        cards:

        - type: horizontal-stack
          cards:
          - type: gauge
            name: Температура
            unit: 'C'
            min: 10
            max: 35
            entity: sensor.temperature_158d0001fa8321
 
          - type: gauge
            name: Влажность
            unit: '%'
            min: 20
            max: 80
            entity: sensor.humidity_158d0001fa8321

          
        - type: glance
          title: Сенсоры
          show_state: false
          entities:
             - entity: binary_sensor.motion_sensor_158d0001a66222
               name: Комната
             - entity: binary_sensor.motion_sensor_158d0001e16204
               name: Коридор
             - entity: binary_sensor.door_window_sensor_158d0001193697
               name: Окно
             - entity: binary_sensor.door_window_sensor_158d0001583c7b
               name: Дверь
             - entity: binary_sensor.water_leak_sensor_158d0001bb60c2
               name: Протечка


  - title: Панель управления
    id: control
    icon: mdi:keyboard    
    
    cards:
    
      - type: vertical-stack
        cards:

        - type: horizontal-stack
          cards:   
          - type: entity-button
            entity: switch.plug_158d00010ec4b8
            name: Увлажнитель
            icon: mdi:air-humidifier
            
          - type: entity-button
            entity: switch.xiaomi_euro
            name: Xiaomi Euro
            icon: mdi:power-socket-eu
          
          - type: entity-button
            entity:  switch.plug_158d00030a6e78
            name: Настольная лампа
            icon: mdi:desk-lamp
            
            
            
            
            

        - type: conditional
          conditions:
           - entity: switch.plug_158d000114a1e1
             state: "on"
           - entity: switch.plug_158d00030a6e78
             state_not: "off"
          card:
            type: glance
            entities:
             - entity: binary_sensor.motion_sensor_158d0001a66222
               name: Комната
             - entity: binary_sensor.motion_sensor_158d0001e16204
               name: Коридор

        - type: entity-filter
          entities:
            - entity: switch.plug_158d00010ec4b8
              name: Увлажнитель воздуха
              icon: mdi:air-humidifier
              secondary_info: last-changed
            - entity: switch.plug_158d000114a1e1
              name: Вентилятор
              icon: mdi:fan
              secondary_info: last-changed
            - entity: switch.plug_158d00030a6e78
              name: Настольная лампа
              icon: mdi:desk-lamp
              secondary_info: last-changed
          state_filter:
                - "on"  

      - type: vertical-stack
        cards:
 
        - type: picture-entity
#          name: Этаж, выход к лифту
          entity: camera.reolink1
          camera_view: live 
          show_state: false
          show_name: false 
 

  - title: Тренды
    id: data
    icon: mdi:chart-gantt

    cards:
    
      - type: vertical-stack
        cards:

        - type: history-graph
          title: 'Давление'
          entities:
              - sensor.pressure_158d0001fa8321
              
        - type: history-graph
          title: 'Изменение температуры'
          entities:
              - entity: sensor.temperature_158d000156e92e
                name: Комната
              - entity: sensor.temperature_158d000171ffde
                name: Коридор

      - type: vertical-stack
        cards:

        - type: sensor
          name: 'Освещенность'
          entity: sensor.illumination_f0b429cc1f11
          graph: line

        - type: weather-forecast
          entity: weather.home  
          
      - type: vertical-stack
        cards:          

        - type: markdown
          content: >
             Обычный текст
    
        - type: markdown
          content: >
             *Текст курсивом*

        - type: markdown
          content: >
             **Жирный текст**
             
        - type: markdown
          content: >
             [Ссылка](https://www.home-assistant.io)

        - type: glance
          title: Сенсоры протечки
          show_state: false
          entities:
             - entity: binary_sensor.water_leak_sensor_158d0001bb60c2
               name: Кухня
             - entity: binary_sensor.water_leak_sensor_158d0001bbeba6
               name: Прачечная
             - entity: binary_sensor.water_leak_sensor_158d0001d72fa2
               name: Туалет
             - entity: binary_sensor.water_leak_sensor_158d0002705b7b
               name: Ванная

        - type: markdown
          content: >
             **Сенсоры протечки**
             
        - type: glance
          show_state: false
          entities:
             - entity: binary_sensor.water_leak_sensor_158d0001bb60c2
               name: Кухня
             - entity: binary_sensor.water_leak_sensor_158d0001bbeba6
               name: Прачечная
             - entity: binary_sensor.water_leak_sensor_158d0001d72fa2
               name: Туалет
             - entity: binary_sensor.water_leak_sensor_158d0002705b7b
               name: Ванная



















